
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNzQwNjgzLCJleHAiOjE3NTE3NDc4ODN9.2fz6oGVaWqJ8qZ1PDPKCdGilWqnweLZtapWg3GzGwT0


###
GET http://localhost:3001/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNzQwNjgzLCJleHAiOjE3NTE3NDc4ODN9.2fz6oGVaWqJ8qZ1PDPKCdGilWqnweLZtapWg3GzGwT0