
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNzQ3OTY3LCJleHAiOjE3NTE3NTUxNjd9.ogKOoiNfuiokeLafiWjdXrdPhzECmoVTQqE20o9mXsA


###
GET http://localhost:3001/api/users/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNzQ3OTY3LCJleHAiOjE3NTE3NTUxNjd9.ogKOoiNfuiokeLafiWjdXrdPhzECmoVTQqE20o9mXsA